# Jekyll Configuration for TVx Documentation

# Theme - Just the Docs (excellent search functionality)
remote_theme: just-the-docs/just-the-docs

# Site settings
title: TVx
description: The warmth of modern nostalgia - IPTV + EPG viewer for Tunarr
url: https://dopeytree.github.io
baseurl: /TVx

# GitHub metadata
repository: dopeytree/TVx

# Logo and branding
# logo: "/assets/images/logo.png"
# favicon_ico: "/assets/images/favicon.ico"

# Color scheme - Custom TVx theme inspired by TeXt
color_scheme: tvx

# Search settings - Just the Docs has built-in search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Heading anchor links
heading_anchors: true

# Aux links (top right)
aux_links:
  "GitHub":
    - "//github.com/dopeytree/TVx"
  "Sponsor ❤️":
    - "//github.com/sponsors/dopeytree"

# Footer content
footer_content: "Copyright &copy; 2025 dopeytree. Distributed under the <a href=\"https://github.com/dopeytree/TVx/blob/main/LICENSE\">PolyForm Noncommercial License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections and navigation
include:
  - _includes/head-custom.html
  - _includes/scripts-custom.html
  - README.md
  #- DOCUMENTATION_UPDATE_SUMMARY.md
  #- BUG_FIX_SYSTEM.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - node_modules/
  - .DS_Store
